language: node_js

node_js:
    - "7"

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    on:
        branch: master

script: npm run build

cache:
    directories:
        - "node_modules"
