= The _OSS-Generic_ Reference Process

The _OSS-Generic Reference Process_ described in this repo documents common practices among several OSS projects
on GitHub, notably, https://github.com/teammates/teammates[TEAMMATES],
https://github.com/se-edu/main[SE-EDU projects], https://github.com/powerpointlabs/powerpointlabs[PowerPointLabs].

== For new contributors

* *<<docs/AdviceForOssBeginners.adoc#,Advice for OSS beginners>>*
* *<<docs/QuestionsIssuesPrs.adoc#asking-a-question,Asking a Question>>*
* *<<docs/QuestionsIssuesPrs.adoc#posting-an-issue,Posting an Issue>>*
* *<<docs/QuestionsIssuesPrs.adoc#submitting-a-pr,Submitting a PR>>*
* *<<docs/AdvancedContributorGuidelines.adoc#,Advanced Contributor Guidelines>>*: Additional guidelines more
experienced contributors are expected to follow.
* https://www.contributor-covenant.org/version/2/0/code_of_conduct[*Code of Conduct*]: To report violations, please post an issue in the respective repository issue tracker.

== General references

* *<<docs/CodingStandards.adoc#,Coding Standards>>*
* *<<docs/HowToGuides.adoc#,'How to' Guides>>*: Detailed help on how to perform some common tasks such as
editing a commit message.
* *<<docs/FormatsAndConventions.adoc#,Formats and Conventions>>*: Formats and conventions for PRs, Issues, Files, etc.
* *<<docs/CommunityStructure.adoc#,Community Structure>>*: Levels, roles, and responsibilities of dev community members.

== For core members

* *<<docs/ReviewingPrs.adoc#,Reviewing PRs>>*: Instructions for PR reviewers
* *<<docs/MergingPrs.adoc#,Merging PRs>>*: Instructions for merging a PR

== For lead members

* *<<docs/OverseeingIssuePrLifeCycle.adoc#,Overseeing Issue/PR Life Cycle>>*: Instructions for team/area leads
on overseeing issue/PR life cycles.
* *<<docs/ManagingReleases.adoc#,Managing Releases>>*: Instructions for managing releases, milestones,
and project schedule.
* *<<docs/DefiningLabels.adoc#,Defining Labels>>*: Instructions for creating labels for the issue tracker.

== Contributing to this repo

We welcome contributions. Just follow the instructions in the above links to submit your contributions as a PR.
